version: 2

sphinx:
  configuration: docs/conf.py

build:
  image: latest

# Install regular dependencies.
python:
  version: 3.7
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs